name: aopserve
description: All Our Photos webserver
version: 0.08.08
homepage: https://www.retired.kiwi/all_our_photos

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  shelf_router: ^0.7.2
  aopcommon:
    path: ../aopcommon
  mysql1:
    path: ../../mysql1_dart

dev_dependencies:
  pedantic: ^1.8.0
