name: aopcommon
description: Common Routines for AllOurPhotos.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  image:
  exif:
  http: ^1.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  lint:
  test: 
